[font]
normal = { family = "IosevkaTerm Nerd Font", style = "Medium" }
bold = { family = "IosevkaTerm Nerd Font", style = "Bold" }
italic = { family = "IosevkaTerm Nerd Font", style = "Italic" }
bold_italic = { family = "IosevkaTerm Nerd Font", style = "Bold Italic" }
